Kalima/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import redirect_to_login
from django.shortcuts import render


urlpatterns = patterns('',
    url(r'^auth/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dictionary/', include('Dictionary.urls', namespace='dictionary')),
    url(r'^inflections/', include('Inflections.urls', namespace='inflections')),
    url(r'^', include('Main.urls', namespace='main')),
)


def handler403(request):
    if request.user.is_authenticated():
        return render(request, 'errors/403.html')
    return redirect_to_login(request.path)

Main/urls.py
from django.conf.urls import patterns, include, url
from Main.views import HomeView, WordView, AddWordView, view_pattern, add_pattern, apply_pattern, edit_pattern, delete_pattern


urlpatterns = patterns('',
    url('^$', HomeView.as_view(), name='home'),
    url('^word/(?P<pk>\d+)/$', WordView.as_view(), name='word'),
    url('^word/add/$', AddWordView.as_view(), name='add_word'),
    url('^pattern/(?P<pk>\d+)/$', view_pattern, name='pattern'),
    url('^pattern/add/$', add_pattern, name='add_pattern'),
    url('^pattern/(?P<pk>\d+)/apply/$', apply_pattern, name='apply_pattern'),
    url('^pattern/(?P<pk>\d+)/edit/$', edit_pattern, name='edit_pattern'),
    url('^pattern/(?P<pk>\d+)/delete/$', delete_pattern, name='delete_pattern'),
)

Kalima/templates/base.html
{% load i18n %}
<html>
<head>
    <title>{% block title %}{% endblock %} - كلمة</title>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
</head>
<body>
<div id="nav-bar">
    <a href="{% url 'main:home' %}">{% trans 'Home' %}</a> &nbsp;
    {% if user.is_authenticated %}
        {% trans 'Current User: ' %}{{ user }}&nbsp;<a href="{% url 'account_logout' %}">{% trans 'Log Out' %}</a>
    {% else %}
        <a href="{% url 'account_login' %}">{% trans 'Log In' %}</a>
    {% endif %}
</div>

{% block content %}{% endblock %}

</body>
<div>
	{% block script %}{% endblock %}
</div>
</html>

Kalima/templates/styled_base.html
{% load i18n %}

<html>
<head>
    <title>{% block title %}أهلا و سهلا{% endblock %} - Kalima</title>

    <link href="/static/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <link href="/static/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    </script>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
        <!--  jquery plguin -->
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <!--start slider -->
    <link rel="stylesheet" href="/static/css/fwslider.css" media="all">
    <script src="/static/js/jquery-ui.min.js"></script>
    <script src="/static/js/css3-mediaqueries.js"></script>
    <script src="/static/js/fwslider.js"></script>
    <!--end slider -->
    <script type="text/javascript">
        $(document).ready(function() {

            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };


            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- start testimonials -->
    <!-- da-slider -->
    <link rel="stylesheet" type="text/css" href="/static/css/slider.css" />
    <script type="text/javascript" src="/static/js/modernizr.custom.28468.js"></script>
    <script type="text/javascript" src="/static/js/jquery.cslider.js"></script>
    <script type="text/javascript">
        $(function() {

            $('#da-slider').cslider({
                autoplay : true,
                bgincrement : 450
            });

        });
    </script>
    <script type="text/javascript">
        $(function() {

            $('#da-slider1').cslider({
                autoplay : true,
                bgincrement : 450
            });

        });
    </script>


</head>


<body>
<!-- start header -->
<div class="header_bg">
	<!-- start header -->
<div class="header_bg">
	<!-----start-conatiner---->
		<div class="container">
			<!-----start-header---->
			<div class="header">
					<!----start-top-nav---->
		      <header id="topnav">
			        <nav>
			        		 <ul>
								<li class="active"><a  href="{% url "dictionary:home" %}">Home</a></li>
								<li><a href="#about" class="scroll">About</a></li>
								<li><a href="#portfolio" class="scroll">Portfolio</a></li>
								<li><a href="#team" class="scroll">Team</a></li>
								<li><a href="#blog" class="scroll">Blog</a></li>
								<li class="last"><a href="#contact" class="scroll">Contact</a></li>
                                <li><h1 class="scroll">{% trans "Current User: " %}</h1><a href="{{ user.get_absolute_url }}">{{ user }}</a></li>
								<div class="clearfix"> </div>
							</ul>
		        	</nav>
			         <h1><a href="index.html"><img src="/static/images/logo.png" alt=""/></a></h1>
			        	<a href="#" id="navbtn">Nav Menu</a>
			       <div class="clearfix"> </div>
		        </header>
		         <!----start-top-nav---->
		    </div>
		   <!-----start-header---->
		</div>
	</div>
		<script type="text/javascript"  src="js/menu.js"></script>
</div>
{% block content %}{% endblock %}
</body>
</html>