Kalima/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import redirect_to_login
from django.shortcuts import render


urlpatterns = patterns('',
    url(r'^auth/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dictionary/', include('Dictionary.urls', namespace='dictionary')),
    url(r'^inflections/', include('Inflections.urls', namespace='inflections')),
    url(r'^', include('Main.urls', namespace='main')),
)


def handler403(request):
    if request.user.is_authenticated():
        return render(request, 'errors/403.html')
    return redirect_to_login(request.path)

Main/urls.py
from django.conf.urls import patterns, include, url
from Main.views import HomeView, WordView, AddWordView, view_pattern, add_pattern, apply_pattern, edit_pattern, delete_pattern


urlpatterns = patterns('',
    url('^$', HomeView.as_view(), name='home'),
    url('^word/(?P<pk>\d+)/$', WordView.as_view(), name='word'),
    url('^word/add/$', AddWordView.as_view(), name='add_word'),
    url('^pattern/(?P<pk>\d+)/$', view_pattern, name='pattern'),
    url('^pattern/add/$', add_pattern, name='add_pattern'),
    url('^pattern/(?P<pk>\d+)/apply/$', apply_pattern, name='apply_pattern'),
    url('^pattern/(?P<pk>\d+)/edit/$', edit_pattern, name='edit_pattern'),
    url('^pattern/(?P<pk>\d+)/delete/$', delete_pattern, name='delete_pattern'),
)

Main/models.py
from django.db import models

# Create your models here.

Main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, DetailView, CreateView, FormView
from Dictionary.models import Word, Pattern
from Dictionary.forms import WordForm, PatternForm, PatternApplyForm


class HomeView(TemplateView):
    template_name = 'home.html'
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['words'] = Word.objects.order_by('?')
        context['patterns'] = Pattern.objects.order_by('?')
        return context


class WordView(DetailView):
    template_name = 'word.html'
    model = Word


class AddWordView(CreateView):
    template_name = 'add_word.html'
    model = Word
    form_class = WordForm


def view_pattern(request, pk):
    '''Detail view for pattern.
    '''
    context = {'pattern': get_object_or_404(Pattern, pk=pk)}
    return render(request, 'pattern.html', context)


def add_pattern(request):
    '''(View) add a pattern using the POST data, if it is valid, then redirect
    to it. If the POST data is not valid, render a page with the invalid fields
    marked.
    '''
    if request.method == 'POST':
        form = PatternForm(request.POST)
        if form.is_valid():
            pattern = form.save()
            return redirect('main:pattern', pk=pattern.pk)
    else:
        form = PatternForm()
    context = {'form': form}
    return render(request, 'add_pattern.html', context)


def edit_pattern(request, pk):
    '''Edit view for pattern
    '''
    pattern = get_object_or_404(Pattern, pk=pk)
    if request.method == 'POST':
        form = PatternForm(request.POST, instance=pattern)
        if form.is_valid():
            form.save(commit=True)
            return redirect('main:pattern', pk=pattern.pk)
    else:
        form = PatternForm(instance=pattern)
    context = {'pattern': pattern, 'form': form}
    return render(request, 'edit_pattern.html', context)


def apply_pattern(request, pk):
    '''View to apply the pattern with id <pk> to the word selected via the
    attached form (instance of PatternApplyForm), and save the result to DB.
    '''
    pattern = get_object_or_404(Pattern, pk=pk)
    if request.method == 'POST':
        form = PatternApplyForm(request.POST)
        if form.is_valid():
            new_word = form.apply(pattern)
            return redirect('main:word', pk=new_word.pk)
    else:
        form = PatternApplyForm()
        queryset = form.fields['stem'].queryset 
        queryset = queryset.filter(pos=pattern.origin_pos)
        # TODO: generate a regex for spellings that match the origin form of
        # this pattern and filter the queryset with it
    context = {'pattern': pattern, 'form': form}
    return render(request, 'apply_pattern.html', context)

def delete_pattern(request, pk):
    '''Delete the Pattern with personal key <pk> (confirmation page on GET,
    perform deletion on POST).
    '''
    pattern = get_object_or_404(Pattern, pk=pk)
    context = {'pattern': pattern}
    if request.method == 'POST':
        pattern.delete()
        return redirect('main:home')
    else:
        return render(request, 'delete_pattern.html', context)

Main/templates/add_pattern.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Add Pattern" %}{% endblock %}

{% block content %}
<form method="POST">
<table>
    {{ form.as_table }}
    <tr>
        <td><input type="submit" label="{% trans "Submit" %}"></td>
    </tr>
    {% csrf_token %}
</table>
{% endblock %}

Main/templates/add_word.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Add Word" %}{% endblock %}

{% block content %}
<form method="POST">
<table>
    {{ form.as_table }}
    <tr>
        <td><input type="submit" label="{% trans "Submit" %}"></td>
    </tr>
    {% csrf_token %}
</table>
{% endblock %}

Main/templates/apply_pattern.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Apply Pattern: " %}{{ pattern }}{% endblock %}

{% block content %}
<form method="POST">
<table>
    {{ form.as_table }}
    <tr>
        <td><input type="submit" label="{% trans "Submit" %}"></td>
    </tr>
    {% csrf_token %}
</table>
{% endblock %}

Main/templates/delete_pattern.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Delete Pattern: " %}{{ pattern.name }}{% endblock %}

{% block content %}
<form method="POST">
    <input type="submit" value="{% trans 'Delete' %}">
    {% csrf_token %}
</form>
{% endblock %}

Main/templates/edit_pattern.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Editing Pattern: " %}{{ pattern.name }}{% endblock %}

{% block content %}
<form method="POST">
<table>
    {{ form.as_table }}
    <tr>
        <td><input type="submit" label="{% trans "Submit" %}"></td>
    </tr>
    {% csrf_token %}
</table>
{% endblock %}

Main/templates/home.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
	<table>
		<tr>
			<th>{% trans 'Word' %}</th>
			<th>{% trans 'Part of Speech' %}</th>
			<th>{% trans 'Definition' %}</th>
		</tr>
		{% for word in words %}
		<tr>
			<td><a href="{% url "main:word" pk=word.pk %}">{{ word.spelling }}</a></td>
			<td>{{ word.get_pos_display }}</td>
			<td>{{ word.definition }}</td>
		</tr>
		{% endfor %}
	</table>
	<table>
		<tr>
			<th rowspan=2>{% trans 'Pattern' %}</th>
			<th colspan=2>{% trans 'Origin' %}</th>
			<th colspan=2>{% trans 'Result' %}</th>
		</tr>
		<tr>
                        <th>{% trans 'Part of Speech' %}</th>
			<th>{% trans 'Form' %}</th>
			<th>{% trans 'Part of Speech' %}</th>
			<th>{% trans 'Form' %}</th>
		</tr>
		{% for pattern in patterns %}
		<tr>
			<td><a href="{% url "main:pattern" pk=pattern.pk %}">{{ pattern.name }}</a></td>
                        <td>{{ pattern.get_origin_pos_display }}</td>
                        <td>{{ pattern.origin_form }}</td>
                        <td>{{ pattern.get_result_pos_display }}</td>
                        <td>{{ pattern.result_form }}</td>
		</tr>
		{% endfor %}
	</table>
		{% if user.is_superuser %}
		<tr>
			<td><a href="{% url 'main:add_word' %}"><i>{% trans 'Add word' %}</i></a>
			<td colspan=2></td>
		</tr>
		<tr>
			<td><a href="{% url 'main:add_pattern' %}"><i>{% trans 'Add pattern' %}</i></a>
			<td colspan=2></td>
		</tr>
		{% endif %}
{% endblock %}

Main/templates/pattern.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Pattern: " %}{{ pattern }}{% endblock %}

{% block content %}
<h1>{{ pattern }}</h1>
<table>
	<tr>
		<td>{% trans 'Origin Pattern' %}</td>
		<td>{{ pattern.origin_form }}</td>
	</tr>
	<tr>
		<td>{% trans 'Result Pattern' %}</td>
		<td>{{ pattern.result_form }}</td>
	</tr>
	<tr>
		<td>{% trans 'Origin Part of Speech' %}</td>
		<td>{{ pattern.get_origin_pos_display }}</td>
	</tr>
	<tr>
		<td>{% trans 'Result Part of Speech' %}</td>
		<td>{{ pattern.get_result_pos_display }}</td>
	</tr>
</table>

<table>
	<tr>
		<th colspan="3">{% trans 'Descendants' %}</th>
	</tr>
	<tr>
		<th>{% trans 'Word' %}</th>
		<th>{% trans 'Part of Speech' %}</th>
		<th>{% trans 'Definition' %}</th>
	</tr>
	{% for descendant in pattern.words.all %}
	<tr>
		<td><a href="{% url "main:word" pk=descendant.pk %}">{{ descendant }}</a></td>
		<td>{{ descendant.get_pos_display }}</td>
		<td>{{ descendant.get_definition_display }}</td>
	</tr>
	{% endfor %}
</table>

{% if user.is_superuser %}
    <a href="{% url 'main:apply_pattern' pk=pattern.pk %}">{% trans 'Apply pattern' %}</a>
    <a href="{% url 'main:edit_pattern' pk=pattern.pk %}">{% trans 'Edit pattern' %}</a>
    <a href="{% url 'main:delete_pattern' pk=pattern.pk %}">{% trans 'Delete pattern' %}</a>
{% endif %}
{% endblock %}

Main/templates/word.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Word: " %}{{ word }}{% endblock %}

{% block content %}
<table>
	<tr>
		<td>{% trans 'Spelling' %}</td>
		<td>{{ word.spelling }}</td>
	</tr>
	<tr>
		<td>{% trans 'Part of Speech' %}</td>
		<td>{{ word.get_pos_display }}</td>
	</tr>
	<tr>
		<td>{% trans 'Definition' %}</td>
		<td>{{ word.definition }}</td>
	</tr>
	{% if word.parent %}
	<tr>
		<td>{% trans 'Parent' %}</td>
		<td><a href="{% url 'main:word' pk=word.parent.pk %}">{{ word.parent }}</a></td>
	</tr>
	{% endif %}
	{% if word.pattern %}
	<tr>
		<td>{% trans 'Pattern' %}</td>
		<td><a href="{% url 'main:pattern' pk=word.pattern.pk %}">{{ word.pattern }}</a></td>
	</tr>
	{% endif %}
</table>
<table>
	<tr>
		<th colspan="3">{% trans 'Descendants' %}</th>
	</tr>
	{% for descendant in word.derivatives.all %}
	<tr>
		<td><a href="{% url 'main:word' pk=descendant.pk %}">{{ descendant.spelling }}</a></td>
		<td>{{ descendant.pos }}</td>
		<td>{{ descendant.definition }}</td>
	</tr>
	{% empty %}
	<tr><td><i>{% trans 'None' %}</i></td></tr>
	{% endfor %}
</table>
{% if word.stem_set.all %}
<table>
	<tr>
		<th colspan="2">{% trans 'Stems' %}</th>
	</tr>
	<tr>
		<td>{% trans 'Spelling' %}</td>
		<td>{% trans 'Attributes' %}</td>
	</tr>
	{% for stem in word.stem_set.all %}
	<tr>
		<td>{{ stem }}</td>
		<td>{{ stem.attributes }}</td>{# TODO: render in human-readable (and translated) format #}
	</tr>
	{% endfor %}
{% endif %}

{% endblock %}